### PR TITLE
Add make target to install Mac dev dependencies

### PR DESCRIPTION
**Pull request by JonnieDoe**
Part of the Ultimate Go course.

### CODE REVIEW

**Comment by JonnieDoe** [comment]
For now, I have added support for Mac only. This can be extended as needed.

**Comment by JonnieDoe** [comment]
cc @ardan-bkennedy

**Comment by ardan-bkennedy** [comment]
I love this. Can you send in the same PR for the service project please and add your name to the CONTRIBUTORS file.

**Comment by ardan-bkennedy** [comment]
What does the double pipe do in this syntax?

**Comment by JonnieDoe** [comment]
> I love this. Can you send in the same PR for the service project please and add your name to the CONTRIBUTORS file.

Sure, will do.

**Comment by ardan-bkennedy** [comment]
I found this 
if the first command succeed the second will never be executed

**Comment by ardan-bkennedy** [comment]
Do we need to run the brew update for this to work?

**Pull request merged**
